apiVersion: v2
name: onelens-agent
description: Helm chart for the OneLens Agent
type: application
version: 0.1.1-beta.4
appVersion: 0.1.1-beta.4
maintainers:
  - name: OneLens
    email: support@onelens.ai

dependencies: 
  - name: onelens-agent-base
    repository: oci://609916866699.dkr.ecr.ap-south-1.amazonaws.com/helm-charts
    version: 0.1.1-beta.3
    alias: onelens-agent
    condition: onelens-agent.enabled
  - name: prometheus
    version: "27.3.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: prometheus-opencost-exporter
    version: "0.1.1"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus-opencost-exporter.enabled
