apiVersion: v2
name: onelensdeployer
description: A Helm chart for deploying Kubernetes Jobs and CronJobs
version: 0.1.0
type: application

maintainers:
  - name: astuto
    email: astuto@astuto.ai

keywords:
  - job
  - cronjob
  - kubernetes
  - helm

templates:
  - name: _helpers.tpl
    path: templates/_helpers.tpl
