# name: Publish Onelensdeployer Helm Charts

# on:
#   push:
#     branches:
#       - master
#     paths:
#       - "charts/onelensdeployer"

# jobs:
#   release:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Setup Helm
#         uses: azure/setup-helm@v3
#         with:
#           version: v3.12.0

#       - name: Package Helm Chart
#         run: |
#           mkdir -p docs
#           helm package charts/onelensdeployer -d docs/

#       - name: Update Helm Repo Index
#         run: |
#           helm repo index docs --url https://astuto-ai.github.io/onelens-installation-scripts/
      
#       - name: Commit and Push Changes
#         run: |
#           git config --global user.name "manoj-astuto"
#           git config --global user.email "manoj.v@astuto.ai"
#           git add docs/
#           git commit -m "Updated Helm charts [CI]"
#           git push origin main
